### ISSUE TITLE
USB power switches short the power supply when disabled

### ISSUE THREAD

**Issue by duckythescientist** [newaetech/phywhispererusb#5] opened 2020-01-24 19:27 UTC
The AP22802 USB power switch chip shorts the output to ground (through ~90ohms) when the output is disabled. This makes sense when they are used to just switch a device on and off, but since the Phywhisperer has the the output of two switches connected together, when one is on, the other one shorts the output to ground.

I noticed this after our board would no longer power the target device. Troubleshooting shows that the two AP22802's are fried.

**Comment by colinoflynn** [comment] 2020-01-24 20:49
Damn - so AP2171AW-7 doesn't have the drain feature and would solve the problem. If you can email sales@newae.com so can figure out RMA on your unit (or best way to solve problem, if you can fix there what you need).

In theory the heating should be:

5V/90ohm = 0.28W. @ "180C/W Thermal Resistance, Junction to Ambient" from datasheet for SOT25 package, means internal device temp would be 50C above ambient. Still way below max junction temp even with some additional heating due to enclosure (say even if 50C in enclosure, junction temp of 100C is below 150C max rating).

Will do more testing here - never saw a problem running them for many hours. A quick finger check doesn't seem to have much heating, thermal camera wasn't working (normal part of check) but will try to get back online or borrow one asap to confirm.

Was it being used any way that would add additional draw? The AP22802 are also EOL suddenly, so I might see if there was some errata/fix they pushed into the new device (AP22811, which still has discharge feature, so the AP2171A is still the best one for future runs).

**Comment by duckythescientist** [comment] 2020-01-25 21:40
The team was using it a lot with a Pi Zero that was being externally powered. However, the AP22802 has reverse current protection, so I'm not exactly sure if or how the backpowering could worsen the situation. And I agree with you on thermals that they should get toasty but not disastrously so. 

We bought a handful of replacement AP22802's, so once those come in, I may swap those in and check the behavior. I'm curious how accurate the 90ohm figure is. I also modified the cable for the Pi Zero by cutting V+ so that backpowering won't be an issue.

AP2171AW-7 could be an ok replacement, but it can only switch half the current of the AP22802.

(A personal note: I've been mostly on a different project, but I will hopefully be back full time on the team using the Phywhisperer in about a week and a half. I'm limited on what debugging/experimentation I can do until that transition, but the rest of the team is picking up some of this in the meantime.)

**Comment by colinoflynn** [comment] 2020-01-26 00:49
Responding mobile so just short note:

AP2191 would have more current capability. Honestly I only thought of 
people using it with standard USB 2 devices (< 500ma) for the most part so 
didn't consider current handling limiting too closely...

I had checked the 90 ohm seems accurate. Measuring current into the sniffer 
port showed constant 51 mA with no load, matches expected closely.

Will try some backpower tests too though, could be something there! Thanks 
for details!

**Comment by colinoflynn** [comment] 2021-02-24 14:25
We've since switched the parts around on units shipped out for the past year - I'm going to close this now. We also confirmed it's too low for it to heat up in practice - so old ones sitting out there should be fine, but in case anyone runs across it we'll of course RMA the units in the future!

**Closed as completed by colinoflynn** 2021-02-24 14:25 UTC
Labels: hardware, critical
