### ISSUE TITLE
External Trigger always enabled

### ISSUE THREAD

**Issue by tresacton** [newaetech/phywhispererusb#2] opened 2019-12-29 22:13 UTC
The external trigger appears to be generated despite the enable flag being set to False. Original line when set to True is as follows:

`# sniff.ipynb`
`...`
`phy.set_trigger(enable=True)`
`...`

Measured with an external scope from the dedicated trigger-out port.

**Comment by jpcrypt** [comment] 2019-12-30 01:03
Hmm, I can't reproduce this -- I checked on both the MCX and 20-pin trigger outs and I get the expected behaviour.  Are you running the latest code? (Shouldn't matter since I don't see any recent commits affecting this.) Can you share the complete notebook?

**Comment by tresacton** [comment] 2020-02-08 04:37
Sorry I've been swamped recently. The notebook I was using has literally no modifications. I can share it all the same when I'm back with that PC if you like. Thanks.

**Comment by jpcrypt** [comment] 2020-02-08 13:46
Sure - just show me how you disabled the trigger?

Also check that your repo up to date. What's the timestamp of your bitfile? Run this in the notebook:
`phy.get_fpga_buildtime()`
and you should get: `'FPGA build time: 12/5/2019, 14:52'`

**Comment by jpcrypt** [comment] 2021-01-06 17:30
Closing because I can't reproduce the problem; the external trigger works correctly as far as I can tell - reopen if there is more information to add.

**Closed as completed by jpcrypt** 2021-01-06 17:30 UTC
